package main

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"os"
	"strings"
	"syscall"
	"time"

	"golang.org/x/oauth2"
)

func basicAuth(next http.HandlerFunc) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		user, pass, ok := r.BasicAuth()
		if !ok || user != *webUsername || pass != *webPassword {
			w.Header().Set("WWW-Authenticate", `Basic realm="smtprelay"`)
			http.Error(w, "Unauthorized", http.StatusUnauthorized)
			return
		}
		next(w, r)
	}
}

func startWebServer() {
	mux := http.NewServeMux()
	mux.HandleFunc("/", basicAuth(handleWebUI))
	mux.HandleFunc("/oauth2", basicAuth(handleOAuth2Page))
	mux.HandleFunc("/oauth2/authorize", basicAuth(handleOAuth2Authorize))
	mux.HandleFunc("/oauth2/callback", basicAuth(handleOAuth2Callback))

	srv := &http.Server{
		Addr:    *webListen,
		Handler: mux,
	}

	log.Info().Str("address", *webListen).Msg("web UI listening")
	if err := srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {
		log.Error().Err(err).Msg("web UI server error")
	}
}

func handleWebUI(w http.ResponseWriter, r *http.Request) {
	switch r.Method {
	case http.MethodGet:
		renderForm(w, "")
	case http.MethodPost:
		saveConfig(w, r)
	default:
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
	}
}

func saveConfig(w http.ResponseWriter, r *http.Request) {
	configPath := flagset.Lookup("config").Value.String()
	if configPath == "" {
		renderForm(w, "Cannot save: no --config file path specified. Restart smtprelay with --config <path> to enable saving.")
		return
	}

	if err := r.ParseForm(); err != nil {
		renderForm(w, fmt.Sprintf("Error parsing form: %v", err))
		return
	}

	fv := func(key string) string {
		return strings.TrimSpace(r.FormValue(key))
	}
	fb := func(key string) string {
		if r.FormValue(key) == "on" {
			return "true"
		}
		return "false"
	}

	lines := []string{
		"# smtprelay configuration",
		"# Generated by web UI on " + time.Now().Format(time.RFC3339),
		"",
		"# Server",
		"hostname = " + fv("hostname"),
		"welcome_msg = " + fv("welcome_msg"),
		"listen = " + fv("listen"),
		"local_cert = " + fv("local_cert"),
		"local_key = " + fv("local_key"),
		"local_forcetls = " + fb("local_forcetls"),
		"",
		"# Remotes",
		"remotes = " + fv("remotes"),
		"strict_sender = " + fb("strict_sender"),
		"remote_certificate = " + fv("remote_certificate"),
		"remote_key = " + fv("remote_key"),
		"",
		"# Access Control",
		"allowed_nets = " + fv("allowed_nets"),
		"allowed_sender = " + fv("allowed_sender"),
		"allowed_recipients = " + fv("allowed_recipients"),
		"allowed_users = " + fv("allowed_users"),
		"",
		"# Aliases & Command",
		"aliases_file = " + fv("aliases_file"),
		"command = " + fv("command"),
		"",
		"# Limits",
		"max_connections = " + fv("max_connections"),
		"max_message_size = " + fv("max_message_size"),
		"max_recipients = " + fv("max_recipients"),
		"",
		"# Timeouts",
		"read_timeout = " + fv("read_timeout"),
		"write_timeout = " + fv("write_timeout"),
		"data_timeout = " + fv("data_timeout"),
		"",
		"# Logging",
		"logfile = " + fv("logfile"),
		"log_format = " + fv("log_format"),
		"log_level = " + fv("log_level"),
		"",
		"# Web UI",
		"web_listen = " + fv("web_listen"),
		"web_username = " + fv("web_username"),
		"web_password = " + fv("web_password"),
		"",
		"# OAuth2",
		"oauth2_client_id = " + fv("oauth2_client_id"),
		"oauth2_client_secret = " + fv("oauth2_client_secret"),
	}

	content := strings.Join(lines, "\n") + "\n"
	if err := os.WriteFile(configPath, []byte(content), 0o600); err != nil {
		renderForm(w, fmt.Sprintf("Error writing config file: %v", err))
		return
	}

	log.Info().Str("path", configPath).Msg("config saved via web UI, restarting")

	go func() {
		time.Sleep(300 * time.Millisecond)
		exe, err := os.Executable()
		if err != nil {
			log.Fatal().Err(err).Msg("cannot get executable path for restart")
		}
		_ = syscall.Exec(exe, os.Args, os.Environ())
	}()

	http.Redirect(w, r, "/", http.StatusSeeOther)
}

func renderForm(w http.ResponseWriter, errMsg string) {
	checked := func(b *bool) string {
		if b != nil && *b {
			return " checked"
		}
		return ""
	}
	val := func(s *string) string {
		if s == nil {
			return ""
		}
		return escapeHTML(*s)
	}
	ival := func(i *int) string {
		if i == nil {
			return ""
		}
		return fmt.Sprintf("%d", *i)
	}

	errHTML := ""
	if errMsg != "" {
		errHTML = `<div class="err">` + escapeHTML(errMsg) + `</div>`
	}

	html := `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>smtprelay configuration</title>
<style>
*{box-sizing:border-box}
body{font-family:system-ui,sans-serif;max-width:800px;margin:2rem auto;padding:0 1rem;color:#222}
h1{font-size:1.4rem;margin-bottom:1.5rem}
h2{font-size:1rem;background:#f4f4f4;padding:.4rem .6rem;border-left:3px solid #666;margin:1.5rem 0 .8rem}
label{display:block;margin-bottom:.9rem}
label span{display:block;font-size:.85rem;color:#555;margin-bottom:.2rem}
input[type=text],input[type=number],input[type=password],textarea{width:100%;padding:.35rem .5rem;border:1px solid #ccc;border-radius:3px;font-size:.95rem;font-family:monospace}
textarea{height:4rem;resize:vertical}
.cb{display:flex;align-items:center;gap:.5rem;margin-bottom:.9rem}
.cb span{font-size:.85rem;color:#555}
button{margin-top:1rem;padding:.5rem 1.5rem;background:#333;color:#fff;border:none;border-radius:3px;cursor:pointer;font-size:1rem}
button:hover{background:#555}
.err{background:#fee;border:1px solid #f99;padding:.6rem .8rem;border-radius:3px;margin-bottom:1rem;color:#900}
</style>
</head>
<body>
<h1>smtprelay configuration</h1>
` + errHTML + `
<form method="POST" action="/">

<h2>Server</h2>
<label><span>hostname</span><input type="text" name="hostname" value="` + val(hostName) + `"></label>
<label><span>welcome_msg</span><input type="text" name="welcome_msg" value="` + val(welcomeMsg) + `"></label>
<label><span>listen (space-separated; prefix starttls:// or tls:// for encrypted)</span><textarea name="listen">` + val(listenStr) + `</textarea></label>
<label><span>local_cert</span><input type="text" name="local_cert" value="` + val(localCert) + `"></label>
<label><span>local_key</span><input type="text" name="local_key" value="` + val(localKey) + `"></label>
<div class="cb"><input type="checkbox" name="local_forcetls" id="local_forcetls"` + checked(localForceTLS) + `><label for="local_forcetls"><span>local_forcetls — force STARTTLS before accepting mail</span></label></div>

<h2>Remotes</h2>
<label><span>remotes (space-separated SMTP URLs)</span><textarea name="remotes">` + val(remotesStr) + `</textarea></label>
<div class="cb"><input type="checkbox" name="strict_sender" id="strict_sender"` + checked(strictSender) + `><label for="strict_sender"><span>strict_sender — only use remotes whose sender matches FROM</span></label></div>
<label><span>remote_certificate</span><input type="text" name="remote_certificate" value="` + val(remoteCert) + `"></label>
<label><span>remote_key</span><input type="text" name="remote_key" value="` + val(remoteKey) + `"></label>

<h2>Access Control</h2>
<label><span>allowed_nets (space-separated CIDR)</span><textarea name="allowed_nets">` + val(allowedNetsStr) + `</textarea></label>
<label><span>allowed_sender (regex)</span><input type="text" name="allowed_sender" value="` + val(allowedSenderStr) + `"></label>
<label><span>allowed_recipients (regex)</span><input type="text" name="allowed_recipients" value="` + val(allowedRecipStr) + `"></label>
<label><span>allowed_users (path to users file)</span><input type="text" name="allowed_users" value="` + val(allowedUsers) + `"></label>

<h2>Aliases &amp; Command</h2>
<label><span>aliases_file</span><input type="text" name="aliases_file" value="` + val(aliasFile) + `"></label>
<label><span>command (path to pipe command)</span><input type="text" name="command" value="` + val(command) + `"></label>

<h2>Limits</h2>
<label><span>max_connections (-1 = unlimited)</span><input type="number" name="max_connections" value="` + ival(maxConnections) + `"></label>
<label><span>max_message_size (bytes)</span><input type="number" name="max_message_size" value="` + ival(maxMessageSize) + `"></label>
<label><span>max_recipients</span><input type="number" name="max_recipients" value="` + ival(maxRecipients) + `"></label>

<h2>Timeouts</h2>
<label><span>read_timeout (e.g. 60s)</span><input type="text" name="read_timeout" value="` + val(readTimeoutStr) + `"></label>
<label><span>write_timeout (e.g. 60s)</span><input type="text" name="write_timeout" value="` + val(writeTimeoutStr) + `"></label>
<label><span>data_timeout (e.g. 5m)</span><input type="text" name="data_timeout" value="` + val(dataTimeoutStr) + `"></label>

<h2>Logging</h2>
<label><span>logfile (empty = stderr)</span><input type="text" name="logfile" value="` + val(logFile) + `"></label>
<label><span>log_format (default / plain / json / pretty)</span><input type="text" name="log_format" value="` + val(logFormat) + `"></label>
<label><span>log_level (trace / debug / info / warn / error / fatal / panic)</span><input type="text" name="log_level" value="` + val(logLevel) + `"></label>

<h2>Web UI &amp; OAuth2 — <a href="/oauth2">Manage Gmail OAuth2 tokens →</a></h2>
<label><span>web_listen (e.g. 127.0.0.1:8080)</span><input type="text" name="web_listen" value="` + val(webListen) + `"></label>
<label><span>web_username</span><input type="text" name="web_username" value="` + val(webUsername) + `"></label>
<label><span>web_password</span><input type="password" name="web_password" value="` + val(webPassword) + `"></label>
<label><span>oauth2_client_id</span><input type="text" name="oauth2_client_id" value="` + val(oauth2ClientID) + `"></label>
<label><span>oauth2_client_secret</span><input type="password" name="oauth2_client_secret" value="` + val(oauth2ClientSecret) + `"></label>

<button type="submit">Save &amp; Restart</button>
</form>
</body>
</html>`

	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	fmt.Fprint(w, html)
}

func escapeHTML(s string) string {
	s = strings.ReplaceAll(s, "&", "&amp;")
	s = strings.ReplaceAll(s, "<", "&lt;")
	s = strings.ReplaceAll(s, ">", "&gt;")
	s = strings.ReplaceAll(s, `"`, "&#34;")
	return s
}

// ---- OAuth2 web flow handlers ----

func handleOAuth2Page(w http.ResponseWriter, r *http.Request) {
	notice := r.URL.Query().Get("notice")
	errMsg := r.URL.Query().Get("error")

	credStatus := "not configured"
	if *oauth2ClientID != "" && *oauth2ClientSecret != "" {
		credStatus = "configured"
	}

	noticeHTML := ""
	if notice != "" {
		noticeHTML = `<div class="ok">` + escapeHTML(notice) + `</div>`
	}
	if errMsg != "" {
		noticeHTML = `<div class="err">` + escapeHTML(errMsg) + `</div>`
	}

	html := `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>smtprelay — OAuth2 / Gmail</title>
<style>
*{box-sizing:border-box}
body{font-family:system-ui,sans-serif;max-width:700px;margin:2rem auto;padding:0 1rem;color:#222}
h1{font-size:1.4rem}
h2{font-size:1rem;background:#f4f4f4;padding:.4rem .6rem;border-left:3px solid #666;margin:1.5rem 0 .8rem}
label{display:block;margin-bottom:.9rem}
label span{display:block;font-size:.85rem;color:#555;margin-bottom:.2rem}
input[type=text]{width:100%;padding:.35rem .5rem;border:1px solid #ccc;border-radius:3px;font-size:.95rem;font-family:monospace}
button{margin-top:.5rem;padding:.5rem 1.5rem;background:#333;color:#fff;border:none;border-radius:3px;cursor:pointer;font-size:1rem}
button:hover{background:#555}
.err{background:#fee;border:1px solid #f99;padding:.6rem .8rem;border-radius:3px;margin-bottom:1rem;color:#900}
.ok{background:#efe;border:1px solid #9c9;padding:.6rem .8rem;border-radius:3px;margin-bottom:1rem;color:#060}
.hint{font-size:.82rem;color:#666;margin-top:.2rem}
a{color:#333}
</style>
</head>
<body>
<h1>OAuth2 / Gmail</h1>
<p><a href="/">← Back to configuration</a></p>
` + noticeHTML + `
<h2>Google API credentials</h2>
<p class="hint">Client credentials status: <strong>` + credStatus + `</strong>. Set <code>oauth2_client_id</code> and <code>oauth2_client_secret</code> on the <a href="/">configuration page</a> or in your config file.</p>

<h2>Authorize a Gmail account</h2>
<p class="hint">After authorization, a token file is written. Reference it in your remote URL:<br>
<code>smtps://smtp.gmail.com:465?auth=xoauth2&amp;email=you@gmail.com&amp;token_file=/path/to/token.json</code></p>
<form method="POST" action="/oauth2/authorize">
<label><span>Gmail address</span><input type="text" name="email" placeholder="you@gmail.com" required></label>
<label><span>Token file path (will be created/overwritten)</span><input type="text" name="token_file" placeholder="/etc/smtprelay/gmail_token.json" required></label>
<button type="submit">Authorize with Google →</button>
</form>
</body>
</html>`

	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	fmt.Fprint(w, html)
}

func handleOAuth2Authorize(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		return
	}
	if *oauth2ClientID == "" || *oauth2ClientSecret == "" {
		http.Redirect(w, r, "/oauth2?error="+url.QueryEscape("oauth2_client_id and oauth2_client_secret must be configured first"), http.StatusSeeOther)
		return
	}

	email := strings.TrimSpace(r.FormValue("email"))
	tokenFile := strings.TrimSpace(r.FormValue("token_file"))
	if email == "" || tokenFile == "" {
		http.Redirect(w, r, "/oauth2?error="+url.QueryEscape("Email and token file path are required"), http.StatusSeeOther)
		return
	}

	state, err := newOAuth2State(email, tokenFile)
	if err != nil {
		http.Redirect(w, r, "/oauth2?error="+url.QueryEscape("Failed to generate state: "+err.Error()), http.StatusSeeOther)
		return
	}

	cfg := gmailOAuth2Config("")
	authURL := cfg.AuthCodeURL(state, oauth2.AccessTypeOffline, oauth2.ApprovalForce)
	http.Redirect(w, r, authURL, http.StatusFound)
}

func handleOAuth2Callback(w http.ResponseWriter, r *http.Request) {
	state := r.URL.Query().Get("state")
	code := r.URL.Query().Get("code")
	errParam := r.URL.Query().Get("error")

	if errParam != "" {
		http.Redirect(w, r, "/oauth2?error="+url.QueryEscape("Google returned an error: "+errParam), http.StatusSeeOther)
		return
	}

	flowState, ok := consumeOAuth2State(state)
	if !ok {
		http.Redirect(w, r, "/oauth2?error="+url.QueryEscape("Invalid or expired state parameter. Please try again."), http.StatusSeeOther)
		return
	}

	cfg := gmailOAuth2Config("")
	token, err := cfg.Exchange(context.Background(), code)
	if err != nil {
		http.Redirect(w, r, "/oauth2?error="+url.QueryEscape("Token exchange failed: "+err.Error()), http.StatusSeeOther)
		return
	}

	if err := saveOAuth2Token(flowState.TokenFile, token); err != nil {
		http.Redirect(w, r, "/oauth2?error="+url.QueryEscape("Failed to save token: "+err.Error()), http.StatusSeeOther)
		return
	}

	log.Info().
		Str("email", flowState.Email).
		Str("token_file", flowState.TokenFile).
		Msg("OAuth2 token saved")

	http.Redirect(w, r, "/oauth2?notice="+url.QueryEscape("Token saved to "+flowState.TokenFile+" for "+flowState.Email), http.StatusSeeOther)
}
