package main

import (
	"context"
	"fmt"
	"html"
	"net/http"
	"net/url"
	"os"
	"strings"
	"syscall"
	"time"

	"golang.org/x/oauth2"
)

func basicAuth(next http.HandlerFunc) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		user, pass, ok := r.BasicAuth()
		if !ok || user != *webUsername || pass != *webPassword {
			w.Header().Set("WWW-Authenticate", `Basic realm="gmailrelay"`)
			http.Error(w, "Unauthorized", http.StatusUnauthorized)
			return
		}
		next(w, r)
	}
}

func startWebServer() {
	mux := http.NewServeMux()
	mux.HandleFunc("/", basicAuth(handleWebUI))
	mux.HandleFunc("/oauth2/authorize", basicAuth(handleOAuth2Authorize))
	mux.HandleFunc("/oauth2/callback", basicAuth(handleOAuth2Callback))

	srv := &http.Server{
		Addr:    *webListen,
		Handler: mux,
	}

	log.Info().Str("address", *webListen).Msg("web UI listening")
	if err := srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {
		log.Error().Err(err).Msg("web UI server error")
	}
}

func handleWebUI(w http.ResponseWriter, r *http.Request) {
	switch r.Method {
	case http.MethodGet:
		renderForm(w, r.URL.Query().Get("error"), r.URL.Query().Get("notice"))
	case http.MethodPost:
		saveConfig(w, r)
	default:
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
	}
}

func saveConfig(w http.ResponseWriter, r *http.Request) {
	configPath := flagset.Lookup("config").Value.String()
	if configPath == "" {
		renderForm(w, "Cannot save: no --config file path specified. Restart gmailrelay with --config <path> to enable saving.", "")
		return
	}

	if err := r.ParseForm(); err != nil {
		renderForm(w, fmt.Sprintf("Error parsing form: %v", err), "")
		return
	}

	fv := func(key string) string {
		return strings.TrimSpace(r.FormValue(key))
	}
	fb := func(key string) string {
		if r.FormValue(key) == "on" {
			return "true"
		}
		return "false"
	}

	lines := []string{
		"# gmailrelay configuration",
		"# Generated by web UI on " + time.Now().Format(time.RFC3339),
		"",
		"# Server",
		"hostname = " + fv("hostname"),
		"welcome_msg = " + fv("welcome_msg"),
		"listen = " + fv("listen"),
		"local_cert = " + fv("local_cert"),
		"local_key = " + fv("local_key"),
		"local_forcetls = " + fb("local_forcetls"),
		"",
		"# Access Control",
		"allowed_nets = " + fv("allowed_nets"),
		"allowed_sender = " + fv("allowed_sender"),
		"allowed_recipients = " + fv("allowed_recipients"),
		"allowed_users = " + fv("allowed_users"),
		"",
		"# Aliases & Command",
		"aliases_file = " + fv("aliases_file"),
		"command = " + fv("command"),
		"",
		"# Limits",
		"max_connections = " + fv("max_connections"),
		"max_message_size = " + fv("max_message_size"),
		"max_recipients = " + fv("max_recipients"),
		"",
		"# Timeouts",
		"read_timeout = " + fv("read_timeout"),
		"write_timeout = " + fv("write_timeout"),
		"data_timeout = " + fv("data_timeout"),
		"",
		"# Logging",
		"logfile = " + fv("logfile"),
		"log_format = " + fv("log_format"),
		"log_level = " + fv("log_level"),
		"",
		"# Web UI",
		"web_listen = " + fv("web_listen"),
		"web_username = " + fv("web_username"),
		"web_password = " + fv("web_password"),
		"",
		"# OAuth2",
		"oauth2_client_id = " + fv("oauth2_client_id"),
		"oauth2_client_secret = " + fv("oauth2_client_secret"),
		"oauth2_redirect_url = " + fv("oauth2_redirect_url"),
		"oauth2_email = " + fv("oauth2_email"),
		"oauth2_token_file = " + fv("oauth2_token_file"),
	}

	content := strings.Join(lines, "\n") + "\n"
	if err := os.WriteFile(configPath, []byte(content), 0o600); err != nil {
		renderForm(w, fmt.Sprintf("Error writing config file: %v", err), "")
		return
	}

	log.Info().Str("path", configPath).Msg("config saved via web UI, restarting")
	renderRestartingPage(w, "Configuration saved. Restarting…")
	scheduleRestart()
}

// renderRestartingPage writes an interstitial page that auto-reloads / after
// the restart window elapses. Without this, the browser would follow a 303
// redirect back to / in milliseconds and hit the still-running old process,
// which renders the form from in-memory config — showing stale values and
// making saves look like they silently failed until the next attempt.
func renderRestartingPage(w http.ResponseWriter, msg string) {
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	fmt.Fprintf(w, `<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8">
<meta http-equiv="refresh" content="2;url=/">
<title>gmailrelay — restarting</title>
<style>body{font-family:system-ui,sans-serif;max-width:600px;margin:4rem auto;padding:0 1rem;color:#222;text-align:center}
.ok{background:#efe;border:1px solid #9c9;padding:1rem;border-radius:3px;color:#060}
.hint{font-size:.85rem;color:#666;margin-top:1rem}</style>
</head><body>
<div class="ok">%s</div>
<p class="hint">Reloading in 2 seconds… <a href="/">click here</a> if the page does not refresh.</p>
</body></html>`, html.EscapeString(msg))
	if f, ok := w.(http.Flusher); ok {
		f.Flush()
	}
}

func scheduleRestart() {
	go func() {
		time.Sleep(300 * time.Millisecond)
		exe, err := os.Executable()
		if err != nil {
			log.Fatal().Err(err).Msg("cannot get executable path for restart")
		}
		_ = syscall.Exec(exe, os.Args, os.Environ())
	}()
}

func renderForm(w http.ResponseWriter, errMsg, noticeMsg string) {
	checked := func(b *bool) string {
		if b != nil && *b {
			return " checked"
		}
		return ""
	}
	val := func(s *string) string {
		if s == nil {
			return ""
		}
		return html.EscapeString(*s)
	}
	ival := func(i *int) string {
		if i == nil {
			return ""
		}
		return fmt.Sprintf("%d", *i)
	}

	statusHTML := ""
	if errMsg != "" {
		statusHTML = `<div class="err">` + html.EscapeString(errMsg) + `</div>`
	}
	if noticeMsg != "" {
		statusHTML += `<div class="ok">` + html.EscapeString(noticeMsg) + `</div>`
	}

	html := `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>gmailrelay configuration</title>
<style>
*{box-sizing:border-box}
body{font-family:system-ui,sans-serif;max-width:800px;margin:2rem auto;padding:0 1rem;color:#222}
h1{font-size:1.4rem;margin-bottom:1.5rem}
h2{font-size:1rem;background:#f4f4f4;padding:.4rem .6rem;border-left:3px solid #666;margin:1.5rem 0 .8rem}
label{display:block;margin-bottom:.9rem}
label span{display:block;font-size:.85rem;color:#555;margin-bottom:.2rem}
input[type=text],input[type=number],input[type=password],textarea{width:100%;padding:.35rem .5rem;border:1px solid #ccc;border-radius:3px;font-size:.95rem;font-family:monospace}
textarea{height:4rem;resize:vertical}
.cb{display:flex;align-items:center;gap:.5rem;margin-bottom:.9rem}
.cb span{font-size:.85rem;color:#555}
button{margin-top:1rem;padding:.5rem 1.5rem;background:#333;color:#fff;border:none;border-radius:3px;cursor:pointer;font-size:1rem}
button:hover{background:#555}
button:disabled{background:#999;cursor:not-allowed}
.err{background:#fee;border:1px solid #f99;padding:.6rem .8rem;border-radius:3px;margin-bottom:1rem;color:#900}
.ok{background:#efe;border:1px solid #9c9;padding:.6rem .8rem;border-radius:3px;margin-bottom:1rem;color:#060}
.hint{font-size:.82rem;color:#666;margin-top:.3rem}
</style>
</head>
<body>
<h1>gmailrelay configuration</h1>
` + statusHTML + `
<form method="POST" action="/">

<h2>Server</h2>
<label><span>hostname</span><input type="text" name="hostname" value="` + val(hostName) + `"></label>
<label><span>welcome_msg</span><input type="text" name="welcome_msg" value="` + val(welcomeMsg) + `"></label>
<label><span>listen (space-separated; prefix starttls:// or tls:// for encrypted)</span><textarea name="listen">` + val(listenStr) + `</textarea></label>
<label><span>local_cert</span><input type="text" name="local_cert" value="` + val(localCert) + `"></label>
<label><span>local_key</span><input type="text" name="local_key" value="` + val(localKey) + `"></label>
<div class="cb"><input type="checkbox" name="local_forcetls" id="local_forcetls"` + checked(localForceTLS) + `><label for="local_forcetls"><span>local_forcetls — force STARTTLS before accepting mail</span></label></div>

<h2>Access Control</h2>
<label><span>allowed_nets (space-separated CIDR)</span><textarea name="allowed_nets">` + val(allowedNetsStr) + `</textarea></label>
<label><span>allowed_sender (regex)</span><input type="text" name="allowed_sender" value="` + val(allowedSenderStr) + `"></label>
<label><span>allowed_recipients (regex)</span><input type="text" name="allowed_recipients" value="` + val(allowedRecipStr) + `"></label>
<label><span>allowed_users (path to users file)</span><input type="text" name="allowed_users" value="` + val(allowedUsers) + `"></label>

<h2>Aliases &amp; Command</h2>
<label><span>aliases_file</span><input type="text" name="aliases_file" value="` + val(aliasFile) + `"></label>
<label><span>command (path to pipe command)</span><input type="text" name="command" value="` + val(command) + `"></label>

<h2>Limits</h2>
<label><span>max_connections (-1 = unlimited)</span><input type="number" name="max_connections" value="` + ival(maxConnections) + `"></label>
<label><span>max_message_size (bytes)</span><input type="number" name="max_message_size" value="` + ival(maxMessageSize) + `"></label>
<label><span>max_recipients</span><input type="number" name="max_recipients" value="` + ival(maxRecipients) + `"></label>

<h2>Timeouts</h2>
<label><span>read_timeout (e.g. 60s)</span><input type="text" name="read_timeout" value="` + val(readTimeoutStr) + `"></label>
<label><span>write_timeout (e.g. 60s)</span><input type="text" name="write_timeout" value="` + val(writeTimeoutStr) + `"></label>
<label><span>data_timeout (e.g. 5m)</span><input type="text" name="data_timeout" value="` + val(dataTimeoutStr) + `"></label>

<h2>Logging</h2>
<label><span>logfile (empty = stderr)</span><input type="text" name="logfile" value="` + val(logFile) + `"></label>
<label><span>log_format (default / plain / json / pretty)</span><input type="text" name="log_format" value="` + val(logFormat) + `"></label>
<label><span>log_level (trace / debug / info / warn / error / fatal / panic)</span><input type="text" name="log_level" value="` + val(logLevel) + `"></label>

<h2>Web UI</h2>
<label><span>web_listen (e.g. 127.0.0.1:8080)</span><input type="text" name="web_listen" value="` + val(webListen) + `"></label>
<label><span>web_username</span><input type="text" name="web_username" value="` + val(webUsername) + `"></label>
<label><span>web_password</span><input type="password" name="web_password" value="` + val(webPassword) + `"></label>

<h2>Gmail OAuth2</h2>
<p class="hint">Fill in all four fields below, then click <strong>Authorize with Google</strong> to complete the OAuth2 flow. A Gmail SMTP remote is configured automatically once authorized.</p>
<label><span>oauth2_client_id</span><input type="text" name="oauth2_client_id" id="oa_cid" value="` + val(oauth2ClientID) + `"></label>
<label><span>oauth2_client_secret</span><input type="password" name="oauth2_client_secret" id="oa_csec" value="` + val(oauth2ClientSecret) + `"></label>
<label><span>oauth2_redirect_url (e.g. http://myhost:8080/oauth2/callback)</span><input type="text" name="oauth2_redirect_url" value="` + val(oauth2RedirectURL) + `"></label>
<label><span>oauth2_email (Gmail address)</span><input type="text" name="oauth2_email" id="oa_email" value="` + val(oauth2Email) + `"></label>
<label><span>oauth2_token_file (path to token JSON file)</span><input type="text" name="oauth2_token_file" id="oa_tfile" value="` + val(oauth2TokenFile) + `"></label>

<button type="submit">Save &amp; Restart</button>
</form>

<form method="POST" action="/oauth2/authorize" id="oauth2form">
<input type="hidden" name="email" id="oa_auth_email">
<input type="hidden" name="token_file" id="oa_auth_tfile">
<button type="submit" id="oa_btn" disabled>Authorize with Google →</button>
</form>

<script>
(function(){
  var cid=document.getElementById('oa_cid'),
      csec=document.getElementById('oa_csec'),
      email=document.getElementById('oa_email'),
      tfile=document.getElementById('oa_tfile'),
      btn=document.getElementById('oa_btn'),
      hEmail=document.getElementById('oa_auth_email'),
      hTfile=document.getElementById('oa_auth_tfile');
  function update(){
    var ok=cid.value.trim()&&csec.value.trim()&&email.value.trim()&&tfile.value.trim();
    btn.disabled=!ok;
    hEmail.value=email.value;
    hTfile.value=tfile.value;
  }
  [cid,csec,email,tfile].forEach(function(el){el.addEventListener('input',update)});
  update();
})();
</script>
</body>
</html>`

	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	fmt.Fprint(w, html)
}


// updateConfigOAuth2 updates oauth2_email and oauth2_token_file in an existing
// INI config file, preserving all other content.
func updateConfigOAuth2(configPath, email, tokenFile string) error {
	data, err := os.ReadFile(configPath)
	if err != nil {
		return err
	}

	lines := strings.Split(string(data), "\n")
	setEmail, setToken := false, false

	for i, line := range lines {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "oauth2_email") && strings.Contains(trimmed, "=") {
			lines[i] = "oauth2_email = " + email
			setEmail = true
		}
		if strings.HasPrefix(trimmed, "oauth2_token_file") && strings.Contains(trimmed, "=") {
			lines[i] = "oauth2_token_file = " + tokenFile
			setToken = true
		}
	}

	if !setEmail {
		lines = append(lines, "oauth2_email = "+email)
	}
	if !setToken {
		lines = append(lines, "oauth2_token_file = "+tokenFile)
	}

	return os.WriteFile(configPath, []byte(strings.Join(lines, "\n")), 0o600)
}

// ---- OAuth2 web flow handlers ----

func handleOAuth2Authorize(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		return
	}
	if *oauth2ClientID == "" || *oauth2ClientSecret == "" {
		http.Redirect(w, r, "/?error="+url.QueryEscape("oauth2_client_id and oauth2_client_secret must be configured first"), http.StatusSeeOther)
		return
	}

	email := strings.TrimSpace(r.FormValue("email"))
	tokenFile := strings.TrimSpace(r.FormValue("token_file"))
	if email == "" || tokenFile == "" {
		http.Redirect(w, r, "/?error="+url.QueryEscape("Email and token file path are required"), http.StatusSeeOther)
		return
	}

	state, err := newOAuth2State(email, tokenFile)
	if err != nil {
		http.Redirect(w, r, "/?error="+url.QueryEscape("Failed to generate state: "+err.Error()), http.StatusSeeOther)
		return
	}

	cfg := gmailOAuth2Config()
	authURL := cfg.AuthCodeURL(state, oauth2.AccessTypeOffline, oauth2.ApprovalForce)
	http.Redirect(w, r, authURL, http.StatusFound)
}

func handleOAuth2Callback(w http.ResponseWriter, r *http.Request) {
	state := r.URL.Query().Get("state")
	code := r.URL.Query().Get("code")
	errParam := r.URL.Query().Get("error")

	if errParam != "" {
		http.Redirect(w, r, "/?error="+url.QueryEscape("Google returned an error: "+errParam), http.StatusSeeOther)
		return
	}

	flowState, ok := consumeOAuth2State(state)
	if !ok {
		http.Redirect(w, r, "/?error="+url.QueryEscape("Invalid or expired state parameter. Please try again."), http.StatusSeeOther)
		return
	}

	cfg := gmailOAuth2Config()
	token, err := cfg.Exchange(context.Background(), code)
	if err != nil {
		http.Redirect(w, r, "/?error="+url.QueryEscape("Token exchange failed: "+err.Error()), http.StatusSeeOther)
		return
	}

	if err := saveOAuth2Token(flowState.TokenFile, token); err != nil {
		http.Redirect(w, r, "/?error="+url.QueryEscape("Failed to save token: "+err.Error()), http.StatusSeeOther)
		return
	}

	log.Info().
		Str("email", flowState.Email).
		Str("token_file", flowState.TokenFile).
		Msg("OAuth2 token saved")

	// Persist oauth2_email and oauth2_token_file into the config file
	// so the Gmail remote is auto-constructed on next start.
	configPath := flagset.Lookup("config").Value.String()
	if configPath != "" {
		if err := updateConfigOAuth2(configPath, flowState.Email, flowState.TokenFile); err != nil {
			log.Error().Err(err).Msg("failed to update config with OAuth2 settings")
		} else {
			log.Info().Str("path", configPath).Msg("config updated with OAuth2 email and token file, restarting")
			renderRestartingPage(w, "Token saved to "+flowState.TokenFile+" for "+flowState.Email+". Restarting to apply…")
			scheduleRestart()
			return
		}
	}

	http.Redirect(w, r, "/?notice="+url.QueryEscape("Token saved to "+flowState.TokenFile+" for "+flowState.Email+"."), http.StatusSeeOther)
}
